"""Update employee table.

Revision ID: 9695656148c3
Revises: 
Create Date: 2025-01-30 22:04:00.955937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9695656148c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_employee_employee_id', ['employee_id']) 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
