"""Add leave_type to LeaveRequest model

Revision ID: cd17d4630644
Revises: 9695656148c3
Create Date: 2025-01-31 21:13:27.150290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd17d4630644'
down_revision = '9695656148c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.String(length=20), nullable=False))  # Set to non-nullable

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###
